loadStopWords <-
function(){
	stopWords <<- c("hustle", "bustle", "none", "business", "classified", 
		"undisclosed", "unknown", "secret", "live", "living",  "lives", "away",
		"far", "across","floating", "adjacent", "near", "nearly", "inner", 
		"outer", "under", "over", "between", "middle", "behind", "front", 
		"top", "bottom", "everywhere", "anywhere", "nowhere", "here", "there", 
		"whenever", "wherever", "somewhere","my", "are", "am", "you", "him", 
		"her", "his","your", "web", "computer", "laptop", "phone", "mobile" , 
		"wide", "cyberspace","internet", "loading", "worldwide", "narnia", 
		"shire", "hogwarts", "batcave" ,"location", "place", "direction", 
		"land", "water", "sun", "world", "globe", "earth", "mercury", "venus", 
		"mars", "jupiter", "saturn", "uranus", "neptune", "planet", "space", 
		"galaxy", "universe", "global", "dmv", "gym", "damn", "fuck", "bitch", 
		"butt", "chocolate", "waffle", "pastry", "cookie", "jar", "facebook", 
		"twitter", "google", "online", "always", "never", "territory", 
		"traffic", "going", "coming", "dream", "dreams", "nightmare", 
		"reality", "graveyard", "ghost", "dreamland", "wonderland", "magic", 
		"fantasy", "fortress", "candyland", "disneyland", "this", "that", 
		"moment","life", "believe","love", "hate", "sin", "heaven", "hell", 
		"angels", "truly", "vacation", "rehab", "desk", "bed", "chair", 
		"book", "move", "moving", "transit", "right", "wrong", "head", "face", 
		"heart", "mind", "spirit", "past", "present", "current", "work", 
		"headquarter", "office", "factory", "farm", "residence", "resident", 
		"home", "house", "backyard", "bedroom", "bathroom", "kitchen", 
		"basement", "room", "with","and" ,"end", "on", "at", "but", "is", 
		"was", "found", "find", "lost", "movies", "cloud", "river", 
		"mountains", "rainbow", "domestic", "international", "wish", 
		"think", "imagine", "imagination", "hole","bubble", "guess", 
		"predict", "edge", "corner", "hot", "cool", "error", "some", 
		"depends", "need", "all", "out", "not")
}
